
services:
  key-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: key-discord-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SERVER_ID=${SERVER_ID}
      - KOREAN_CHANNEL_ID=${KOREAN_CHANNEL_ID}
      - ENGLISH_CHANNEL_ID=${ENGLISH_CHANNEL_ID}
      - JAPANESE_CHANNEL_ID=${JAPANESE_CHANNEL_ID}
      - CHINESE_CHANNEL_ID=${CHINESE_CHANNEL_ID}
      - RATE_LIMIT_PER_MINUTE=${RATE_LIMIT_PER_MINUTE:-30}
      - MAX_DAILY_REQUESTS=${MAX_DAILY_REQUESTS:-1000}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    env_file:
      - .env
    networks:
      - key-bot-network

networks:
  key-bot-network:
    driver: bridge

volumes:
  logs:
  data: